# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixa',
            options={'ordering': ['descricao']},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['descricao']},
        ),
        migrations.RenameField(
            model_name='equipamento',
            old_name='quantidade',
            new_name='quantidade_disponivel',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_registro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='quantidade_total',
            field=models.IntegerField(default=0),
        ),
    ]
