# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0002_auto_20170311_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='quantidade_disponivel',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
