# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0003_auto_20170311_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arduino.Caixa'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='arduino.Categoria'),
            preserve_default=False,
        ),
    ]
